name: Build Native Modules

on:
  push:
    branches:
      - main
      - gh-actions-testing
#   pull_request:
#     branches:
#       - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2025, windows-11-arm]
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node-gyp and node-addon-api
        run: |
          npm install -g node-gyp
          npm install node-addon-api

      - name: Rename binding.gyp.dist to binding.gyp
        run: mv binding.gyp.dist binding.gyp
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Build native modules
        run: npm run build-win10

      - name: Archive build output
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.os }}-${{ matrix.node-version }}
          path: |
            native/prebuilt/
